[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
opacity = 0.96
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "FiraCode Nerd Font"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[general]
live_config_reload = true
